// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordikAdventuresAPI.Modeles;

#nullable disable

namespace NordikAdventuresAPI.Migrations
{
    [DbContext(typeof(BdContexteNordik))]
    partial class BdContexteNordikModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Achats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CoutHistorique")
                        .HasColumnType("float");

                    b.Property<int>("IdCommandeFournisseur")
                        .HasColumnType("int");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdCommandeFournisseur");

                    b.HasIndex("SKU");

                    b.ToTable("TableAchats");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.ActivitesClients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdEmploye")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdEmploye");

                    b.ToTable("TableActivitesClients");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.ActivitesStocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SKU");

                    b.ToTable("TableActivitesStocks");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TablesCategories");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Clients", b =>
                {
                    b.Property<string>("ClientID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Satisfaction")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("TablesClients");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.CommandesFournisseurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLimitePaiements")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFournisseur")
                        .HasColumnType("int");

                    b.Property<double>("MontantDu")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valider")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdFournisseur");

                    b.ToTable("TablesCommandesFournisseurs");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Employes", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AccesClient")
                        .HasColumnType("bit");

                    b.Property<bool>("AccesFinances")
                        .HasColumnType("bit");

                    b.Property<bool>("AccesProduits")
                        .HasColumnType("bit");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TablesEmployes");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.FacturesClients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLimitePaiement")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MontantDu")
                        .HasColumnType("float");

                    b.Property<int>("Satisfaction")
                        .HasColumnType("int");

                    b.Property<double>("SousTotal")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Taxes")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("TablesFacturesClients");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Fournisseurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RistourneFournisseur")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TablesFournisseurs");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.PaiementsClients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdFacture")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("montantPayer")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdFacture");

                    b.ToTable("TablesPaiementsClients");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.PaiementsFournisseurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("int");

                    b.Property<double>("Paiement")
                        .HasColumnType("float");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCommande");

                    b.ToTable("TablesPaiementsFournisseurs");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.ParamFisc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nom")
                        .HasColumnType("int");

                    b.Property<float>("TauxTaxe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TablesParamFisc");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Payes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdEmploye")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Paye")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdEmploye");

                    b.ToTable("TablesPayes");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Produits", b =>
                {
                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeFournisseur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CoutAchat")
                        .HasColumnType("float");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<int>("IdFournisseur")
                        .HasColumnType("int");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Poids")
                        .HasColumnType("real");

                    b.Property<double>("PrixVente")
                        .HasColumnType("float");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.HasKey("SKU");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdFournisseur");

                    b.ToTable("TablesProduits");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Stocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelaiLivraison")
                        .HasColumnType("int");

                    b.Property<string>("Entrepot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<int>("QteReserve")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SeuilMinimun")
                        .HasColumnType("int");

                    b.Property<int>("SeuilReaprovisionnement")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateEntree")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("TablesStocks");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Ventes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdFacture")
                        .HasColumnType("int");

                    b.Property<double>("PrixVenteHistorique")
                        .HasColumnType("float");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdFacture");

                    b.HasIndex("SKU");

                    b.ToTable("TablesVentes");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Achats", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.CommandesFournisseurs", "CommandeFournisseur")
                        .WithMany("LesAchats")
                        .HasForeignKey("IdCommandeFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NordikAdventuresAPI.Modeles.Produits", "LeProduit")
                        .WithMany("LesAchats")
                        .HasForeignKey("SKU")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CommandeFournisseur");

                    b.Navigation("LeProduit");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.ActivitesClients", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Clients", "LeClient")
                        .WithMany("LesActivitesDuClient")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NordikAdventuresAPI.Modeles.Employes", "LEmploye")
                        .WithMany("LesActivitesDuClient")
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LEmploye");

                    b.Navigation("LeClient");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.ActivitesStocks", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Produits", "LeProduit")
                        .WithMany("MouvementsStocks")
                        .HasForeignKey("SKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeProduit");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.CommandesFournisseurs", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Fournisseurs", "Fournisseur")
                        .WithMany("LesCommandesAuxFournisseur")
                        .HasForeignKey("IdFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.FacturesClients", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Clients", "LeClient")
                        .WithMany("LesFacturesClient")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeClient");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.PaiementsClients", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.FacturesClients", "LaFactureClient")
                        .WithMany("LesPaiementsClient")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaFactureClient");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.PaiementsFournisseurs", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.CommandesFournisseurs", "LesCommandesFournisseurs")
                        .WithMany("LesPaiementsFournisseur")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LesCommandesFournisseurs");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Payes", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Employes", "LEmploye")
                        .WithMany("LesPayesDEmploye")
                        .HasForeignKey("IdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LEmploye");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Produits", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Categories", "LaCategorie")
                        .WithMany("LesProduits")
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NordikAdventuresAPI.Modeles.Fournisseurs", "LeFounisseur")
                        .WithMany("LesProduits")
                        .HasForeignKey("IdFournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaCategorie");

                    b.Navigation("LeFounisseur");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Stocks", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.Produits", "LeProduit")
                        .WithOne("LeStocks")
                        .HasForeignKey("NordikAdventuresAPI.Modeles.Stocks", "SKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeProduit");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Ventes", b =>
                {
                    b.HasOne("NordikAdventuresAPI.Modeles.FacturesClients", "LaFactureClient")
                        .WithMany("LesVentes")
                        .HasForeignKey("IdFacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NordikAdventuresAPI.Modeles.Produits", "LeProduit")
                        .WithMany("LesVentes")
                        .HasForeignKey("SKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaFactureClient");

                    b.Navigation("LeProduit");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Categories", b =>
                {
                    b.Navigation("LesProduits");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Clients", b =>
                {
                    b.Navigation("LesActivitesDuClient");

                    b.Navigation("LesFacturesClient");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.CommandesFournisseurs", b =>
                {
                    b.Navigation("LesAchats");

                    b.Navigation("LesPaiementsFournisseur");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Employes", b =>
                {
                    b.Navigation("LesActivitesDuClient");

                    b.Navigation("LesPayesDEmploye");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.FacturesClients", b =>
                {
                    b.Navigation("LesPaiementsClient");

                    b.Navigation("LesVentes");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Fournisseurs", b =>
                {
                    b.Navigation("LesCommandesAuxFournisseur");

                    b.Navigation("LesProduits");
                });

            modelBuilder.Entity("NordikAdventuresAPI.Modeles.Produits", b =>
                {
                    b.Navigation("LeStocks")
                        .IsRequired();

                    b.Navigation("LesAchats");

                    b.Navigation("LesVentes");

                    b.Navigation("MouvementsStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
